### ISSUE TITLE
performance: stress test

### ISSUE THREAD

**Issue by viveknathani** [viveknathani/teachyourselfmath#10]

**Comment by Advait1306** [comment]
Don't worry about these, it's good enough to get started :)

**Comment by viveknathani** [comment]
> Don't worry about these, it's good enough to get started :)

@Advait1306 - yew, keeping this as an open issue to be solved later. migrating to a kind of infra where i can plug in my own APM setup at low cost should help me gain better visibility and hence fix these performance issues. only a matter of time.
