### ISSUE TITLE
chore: docker setup for local development

### ISSUE THREAD

**Issue by Badhan-abhishek** [viveknathani/teachyourselfmath#13]
Docker setup with redis, database & adminer for local development.

**Comment by Badhan-abhishek** [comment]
will open PR soon.

**Comment by viveknathani** [comment]
hey @Badhan-abhishek! thank you for taking this up, looking forward to your contributions!

**Comment by Badhan-abhishek** [comment]
I do have an initial setup ready. Will open PR tonight.

**Comment by Badhan-abhishek** [comment]
PR created #15

**Comment by viveknathani** [comment]
to understand why this issue is being marked as closed, see [this](https://github.com/viveknathani/teachyourselfmath/pull/15#issuecomment-2226854491).
