### ISSUE TITLE
chore: open source

### ISSUE THREAD

**Issue by viveknathani** [viveknathani/teachyourselfmath#9]
1. MIT license - DONE
2. README - DONE
    - what
    - why
    - how
    - instructions to build from the source
    - ~how to contribute~ - this is silly, people know this already
3. GitHub action to build the code on every pull request. - DONE
4. links and descriptions - DONE
5. accessible on multiple pages/profiles - DONE
6. tagging via git - DONE

**Comment by BibiClover** [comment]
I do believe having a CONTRIBUTING.md file would be beneficial if you want other people to contribute. 
Even if you don't put anything in the file, some people do look for it to see if the repo is open to contributions.
